name: Release

on: 
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Release
        run: ./build.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/systemaudio dist/systemaudio.alfredworkflow