name: Release

on: 
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Release
        run: swift build --configuration release
      - name: Set binary path name
        run: echo "::set-env name=BINARY_PATH::$(swift build --configuration release --show-bin-path)/systemaudio"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{env.BINARY_PATH}}